# Generated by Django 5.1.1 on 2024-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("nickname", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=15)),
                ("Phone_number", models.CharField(max_length=100)),
                ("Last_login", models.BooleanField(default=False)),
                ("Is_staff", models.BooleanField(default=False)),
                ("Is_admin", models.BooleanField(default=False)),
                ("Is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
