# Generated by Django 5.1.1 on 2024-09-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="Is_active",
            new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="username",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="Phone_number",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="users",
            name="Is_staff",
        ),
        migrations.RemoveField(
            model_name="users",
            name="Last_login",
        ),
        migrations.AddField(
            model_name="users",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AddField(
            model_name="users",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
