# Generated by Django 5.1.1 on 2024-09-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_is_active_users_is_staff_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="Is_admin",
            new_name="is_admin",
        ),
    ]
