# Generated by Django 5.1.1 on 2024-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="계좌번호"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("kakao", "카카오뱅크"),
                            ("kb", "국민은행"),
                            ("nh", "농협은행"),
                            ("ibk", "기업은행"),
                        ],
                        max_length=20,
                        verbose_name="은행 코드",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("checking", "입출금통장"), ("savings", "저축통장")],
                        max_length=20,
                        verbose_name="계좌 종류",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="잔액"
                    ),
                ),
            ],
        ),
    ]
