# Generated by Django 5.1.1 on 2024-09-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_description",
            field=models.CharField(max_length=20),
        ),
    ]
